#!/usr/bin/env python3
"""UR5e Trajectory Tracking and Data Collection using Position Control (servoJ).
Uses the trajectory generated by get_ref.py starting from the current joint position.
"""

import time
import numpy as np
import pandas as pd
import yaml
import matplotlib.pyplot as plt
from pathlib import Path
from rtde_control import RTDEControlInterface
from rtde_receive import RTDEReceiveInterface
from get_ref import generate_trajectory

ROBOT_IP = "192.168.56.101"

def main():
    print(f"[INFO] Connecting to robot {ROBOT_IP}...")
    rtde_c = RTDEControlInterface(ROBOT_IP)
    rtde_r = RTDEReceiveInterface(ROBOT_IP)
    
    # 1. 获取初始位置
    q_start = np.array(rtde_r.getActualQ())
    print(f"[INFO] Current position: {q_start}")
    
    # 2. 生成参考轨迹 (从当前角度开始)
    print("[INFO] Generating trajectory...")
    t_vec, q_ref_vec, dq_ref_vec, ddq_ref_vec, stage_vec = generate_trajectory(q_init_5=q_start[5], num_scan_points=10)
    
    # 3. 加载刚才测量的 Kt 值
    kt_file = Path("Config/Kt_calibration_results.yaml")
    if kt_file.exists():
        with open(kt_file, 'r') as f:
            kt_data = yaml.safe_load(f)
            KT_LIST = kt_data.get("Kt", [11.0, 11.0, 11.0, 8.4, 8.4, 8.4])
            print(f"[INFO] Loaded Kt calibration: {KT_LIST}")
    else:
        KT_LIST = [11.0, 11.0, 11.0, 8.4, 8.4, 8.4] # 缺省值
        print("[WARN] No Kt calibration file found. Using nominal values.")

    # 4. 可视化设置
    plt.ion()
    fig, axs = plt.subplots(4, 1, figsize=(10, 12), sharex=True)
    line_q_des, = axs[0].plot([], [], 'r--', label='Des Pos')
    line_q_act, = axs[0].plot([], [], 'b-', label='Act Pos')
    line_dq_act, = axs[1].plot([], [], 'b-', label='Act Vel')
    line_tau_act, = axs[2].plot([], [], 'k-', label='Torque (Nm)')
    line_stage, = axs[3].plot([], [], 'g-', label='Stage')
    
    for ax in axs: ax.grid(True); ax.legend(loc='upper right')
    axs[0].set_ylabel('Pos (rad)'); axs[1].set_ylabel('Vel (rad/s)')
    axs[2].set_ylabel('Torque (Nm)'); axs[3].set_ylabel('Stage')
    axs[3].set_xlabel('Time (s)')

    dt = 0.002 # 匹配轨迹生成的 dt
    plot_dt = 0.1 # 10Hz 刷新绘图
    next_plot_time = 0.0
    lookahead_time = 0.1
    gain = 300.0
    
    data_log = []
    
    print("[INFO] Starting servoJ tracking loop (500Hz)...")
    try:
        start_wall_time = time.perf_counter()
        for i in range(len(t_vec)):
            loop_start = time.perf_counter()
            t_now = t_vec[i]
            
            q_target = q_start.copy()
            q_target[5] = q_ref_vec[i]
            
            rtde_c.servoJ(q_target, 0.0, 0.0, dt, lookahead_time, gain)
            
            q_act = rtde_r.getActualQ()
            dq_act = rtde_r.getActualQd()
            i_act = np.array(rtde_r.getActualCurrent())
            tau_act = i_act * np.array(KT_LIST)
            
            # 记录数据
            item = [t_now, q_ref_vec[i], q_act[5], dq_ref_vec[i], dq_act[5], ddq_ref_vec[i], tau_act[5], stage_vec[i]]
            data_log.append(item)
            
            # 实时绘图 (降低频率以保证实时性)
            if t_now >= next_plot_time:
                win_size = 5000 # 记录 10 秒的数据用于回传显示
                recent_data = np.array(data_log[-win_size:])
                if len(recent_data) > 0:
                    t_win = recent_data[:, 0]
                    line_q_des.set_data(t_win, recent_data[:, 1])
                    line_q_act.set_data(t_win, recent_data[:, 2])
                    line_dq_act.set_data(t_win, recent_data[:, 4])
                    line_tau_act.set_data(t_win, recent_data[:, 6])
                    line_stage.set_data(t_win, recent_data[:, 7])
                    
                    for ax in axs: 
                        ax.relim()
                        ax.autoscale_view()
                    axs[-1].set_xlim(left=max(0, t_now - 10), right=max(10, t_now))
                    fig.canvas.draw_idle()
                    fig.canvas.flush_events()
                next_plot_time += plot_dt
            
            # 维持频率
            elapsed = time.perf_counter() - loop_start
            if elapsed < dt:
                time.sleep(dt - elapsed)
                
    except KeyboardInterrupt:
        print("\n[INFO] Stopped by user.")
    finally:
        print("[INFO] Stopping servoJ and saving data...")
        rtde_c.servoStop()
        rtde_c.stopScript()
        
        if data_log:
            df = pd.DataFrame(data_log, columns=[
                'time', 'q_des', 'q_act', 'dq_des', 'dq_act', 'ddq_des', 'torque', 'stage'
            ])
            save_path = Path("Data")
            save_path.mkdir(exist_ok=True)
            df.to_csv(save_path / "Collection_data.csv", index=False)
            print(f"[INFO] Data saved to {save_path / 'Collection_data.csv'}")

if __name__ == "__main__":
    main()
